id: phyloseq-step-2-phylogenetic-tree
name: 'Phyloseq -> Step 2: Phylogenetic Tree'
description: Task template generating phylogenetic tree using DADA2 output
is_active: true
project_type: 11
param_groups:
- name: inputs
  params:
  - name: dada2Artifacts
    description: Artifacts which contain the output of DADA2 run.
    value: null
    data_type: int
    required: true
- name: outputs
  params:
  - name: outputDataset
    description: Dataset with outputs of this task.
    value: null
    data_type: dataset
    required: false
